"""Regenerate the golden fixtures from the Python reference implementation.

    python generate_goldens.py <path-to-senp.ai/backend>

The reference services depend on numpy alone - no YOLO, no video, no corpus - so the
fixtures can be produced anywhere the backend is checked out.

Inputs are chosen to sit exactly on the decision boundaries a frames-to-milliseconds port
can slip across: a gap of 4 against one of 5, a low run of 7 against one of 8, a recovery
of 5 against one of 6, and runs touching either end of a clip. Real footage does not
reliably contain those cases.

Output is written verbatim, including the reference's habit of writing 0.0 for a missing
landmark. The Kotlin side keeps missing as NaN and applies that one documented divergence
when comparing, so these files stay a faithful record of what the reference does.
"""

import sys
from pathlib import Path

import numpy as np

DT_MS = 100  # uniform sampling, so the reference's per-frame constants map exactly


def fmt(values):
    return " ".join(f"{float(v):.9g}" for v in values)


def smoothing_cases(SmoothService):
    service = SmoothService("ema_window")
    alpha, max_gap, min_conf = 0.7, 4, 0.5

    def case(name, values, gated):
        frames = len(values)
        xy = np.zeros((frames, 1, 2), dtype=np.float32)
        conf = np.ones((frames, 1), dtype=np.float32)
        for t, v in enumerate(values):
            xy[t, 0, 0] = v
            xy[t, 0, 1] = 2.0 * v
        for t, c in gated.items():
            conf[t, 0] = c
        result = service.run(xy, conf, min_conf, alpha, max_gap)
        return [
            f"case {name}",
            f"dt_ms {DT_MS}",
            f"alpha {alpha}",
            f"max_gap_frames {max_gap}",
            f"min_conf {min_conf}",
            f"in_x {fmt(xy[:, 0, 0])}",
            f"in_conf {fmt(conf[:, 0])}",
            f"out_x {fmt(result.keypoints_xy[:, 0, 0])}",
            f"out_conf {fmt(result.keypoints_conf[:, 0])}",
        ]

    ramp = [float(t) for t in range(14)]
    low = 0.1
    return [
        case("gap_of_4_is_repaired", ramp, {t: low for t in (4, 5, 6, 7)}),
        case("gap_of_5_is_not_repaired", ramp, {t: low for t in (4, 5, 6, 7, 8)}),
        case("leading_gap_is_not_extrapolated", ramp, {0: low, 1: low}),
        case("trailing_gap_is_not_extrapolated", ramp, {12: low, 13: low}),
        case("confidence_ceiling_binds", ramp, {5: 0.45, 6: 0.45}),
        case("whole_track_missing", ramp, {t: low for t in range(14)}),
        case("alternating_single_gaps", ramp, {t: low for t in range(1, 14, 2)}),
        case("no_gaps_is_plain_ema", ramp, {}),
    ]


def quality_cases(QualityGateService):
    service = QualityGateService()
    min_conf, blind, usable = 0.5, 0.40, 0.55
    min_blind_frames, recover_frames = 8, 6
    joints = 17

    def case(name, per_frame):
        conf = np.zeros((len(per_frame), joints), dtype=np.float32)
        for t, c in enumerate(per_frame):
            conf[t, :] = c
        result = service.run(conf, min_conf, blind, usable, min_blind_frames, recover_frames)
        return [
            f"case {name}",
            f"dt_ms {DT_MS}",
            f"min_conf {min_conf}",
            f"blind_threshold {blind}",
            f"usable_threshold {usable}",
            f"min_blind_frames {min_blind_frames}",
            f"recover_frames {recover_frames}",
            f"in_conf {fmt(per_frame)}",
            f"out_quality {fmt(result.frame_quality)}",
            f"out_visible {' '.join('1' if v else '0' for v in result.visible_mask)}",
        ]

    good, bad = 0.9, 0.3
    return [
        case("low_run_of_7_does_not_trip", [good] * 6 + [bad] * 7 + [good] * 6),
        case("low_run_of_8_trips", [good] * 6 + [bad] * 8 + [good] * 6),
        case("recovery_of_5_stays_blind", [good] * 6 + [bad] * 10 + [good] * 5 + [bad] * 4),
        case("recovery_of_6_recovers", [good] * 6 + [bad] * 10 + [good] * 6 + [bad] * 4),
        case("low_run_starts_the_clip", [bad] * 10 + [good] * 10),
        case("blind_until_the_end", [good] * 6 + [bad] * 12),
        case("all_good", [good] * 12),
    ]


def write(path, header, cases):
    lines = [f"# {header}", "# Generated by generate_goldens.py from the Python reference.", ""]
    for block in cases:
        lines.extend(block)
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {path.name}: {len(cases)} cases")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    backend = Path(sys.argv[1]).resolve()
    sys.path.insert(0, str(backend))
    from app.services.quality_gate_service import QualityGateService
    from app.services.smooth_service import SmoothService

    here = Path(__file__).parent
    write(here / "smoothing.txt", "Smoothing goldens", smoothing_cases(SmoothService))
    write(here / "quality.txt", "Quality gate goldens", quality_cases(QualityGateService))


if __name__ == "__main__":
    main()
