package ai.senp.motion

import ai.senp.motion.quality.QualityGate
import ai.senp.motion.smoothing.Smoothing
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Replays the Python reference's own output, case by case.
 *
 * The fixtures in `resources/golden` are generated by `generate_goldens.py` from the
 * reference services, on inputs chosen to sit exactly on the boundaries a
 * frames-to-milliseconds port can slip across. Sampling is uniform, so the two
 * implementations must agree exactly rather than approximately: at a fixed interval
 * `alpha(dt) = 1 - exp(-dt/tau)` collapses back to the reference's per-frame alpha, and the
 * duration thresholds were chosen to trip on the same samples.
 *
 * This also puts the frame-to-millisecond conversions themselves under test — the fixtures
 * carry the reference's frame counts, and the conversion happens here.
 *
 * One divergence is expected and asserted rather than tolerated: the reference writes 0.0
 * with zero confidence for a missing landmark, which cannot be told apart from a landmark
 * legitimately at the origin. We keep missing as NaN.
 */
class GoldenParityTest {

    private val tolerance = 1e-4f

    private class Case(private val fields: Map<String, List<String>>) {
        val name: String get() = text("case")
        fun text(key: String) = fields[key]?.firstOrNull() ?: fail("case is missing '$key'")
        fun long(key: String) = text(key).toLong()
        fun float(key: String) = text(key).toFloat()
        fun floats(key: String) = (fields[key] ?: fail("case is missing '$key'")).map { it.toFloat() }
        fun flags(key: String) = (fields[key] ?: fail("case is missing '$key'")).map { it == "1" }
    }

    private fun cases(resource: String): List<Case> {
        val text = checkNotNull(javaClass.getResourceAsStream(resource)) { "missing $resource" }
            .bufferedReader().readText()
        return text.split(Regex("\\r?\\n\\s*\\r?\\n"))
            .map { block -> block.lines().filter { it.isNotBlank() && !it.startsWith("#") } }
            .filter { it.isNotEmpty() }
            .map { lines ->
                Case(lines.associate { line ->
                    val parts = line.trim().split(Regex("\\s+"))
                    parts[0] to parts.drop(1)
                })
            }
            .also { assertTrue(it.isNotEmpty(), "no cases parsed from $resource") }
    }

    @Test
    fun `smoothing matches the reference on every golden case`() {
        val cases = cases("/golden/smoothing.txt")
        for (case in cases) {
            val dtMs = case.long("dt_ms")
            val inX = case.floats("in_x")
            val inConf = case.floats("in_conf")
            val outX = case.floats("out_x")
            val outConf = case.floats("out_conf")
            val frames = inX.size

            val result = Smoothing.smoothClip(
                timestampsMs = LongArray(frames) { it * dtMs },
                // One landmark; y carries 2x to catch a coordinate mix-up.
                xyz = Array(frames) { floatArrayOf(inX[it], 2f * inX[it], 0f) },
                confidence = Array(frames) { floatArrayOf(inConf[it]) },
                minConfidence = case.float("min_conf"),
                // A gap of N frames spans (N+1) sample intervals between the samples that
                // bracket it, which is the distance the interpolation is drawn across.
                maxGapMs = (case.long("max_gap_frames") + 1) * dtMs,
                tauMs = Smoothing.tauFromAlpha(case.float("alpha"), dtMs.toFloat()),
            )

            for (t in 0 until frames) {
                val where = "${case.name}[$t]"
                val x = result.xyz[t][0]
                if (outConf[t] == 0f) {
                    assertTrue(x.isNaN(), "$where: reference dropped this sample, expected NaN, was $x")
                    assertEquals(0f, result.confidence[t][0], tolerance, "$where confidence")
                } else {
                    assertEquals(outX[t], x, tolerance, "$where x")
                    assertEquals(2f * outX[t], result.xyz[t][1], tolerance * 2f, "$where y")
                    assertEquals(outConf[t], result.confidence[t][0], tolerance, "$where confidence")
                }
            }
        }
        assertEquals(8, cases.size, "expected every generated smoothing case to be exercised")
    }

    @Test
    fun `quality gate matches the reference on every golden case`() {
        val cases = cases("/golden/quality.txt")
        for (case in cases) {
            val dtMs = case.long("dt_ms")
            val inConf = case.floats("in_conf")
            val outQuality = case.floats("out_quality")
            val outVisible = case.flags("out_visible")
            val frames = inConf.size
            val joints = 17 // the reference's COCO-17 layout

            val result = QualityGate.evaluate(
                timestampsMs = LongArray(frames) { it * dtMs },
                confidence = Array(frames) { t -> FloatArray(joints) { inConf[t] } },
                minConfidence = case.float("min_conf"),
                blindThreshold = case.float("blind_threshold"),
                usableThreshold = case.float("usable_threshold"),
                blindEnterMs = case.long("min_blind_frames") * dtMs,
                blindRecoverMs = case.long("recover_frames") * dtMs,
                // COCO-17 arm indices, the adapter for reference-shaped inputs. Confidence is
                // uniform across joints here, so this only documents the mapping.
                weights = QualityGate.Weights(focusLandmarks = listOf(5, 6, 7, 8, 9, 10)),
            )

            for (t in 0 until frames) {
                assertEquals(outQuality[t], result.frameQuality[t], tolerance, "${case.name}[$t] quality")
                assertEquals(outVisible[t], result.visible[t], "${case.name}[$t] visible")
            }
        }
        assertEquals(7, cases.size, "expected every generated quality case to be exercised")
    }
}
